### ISSUE TITLE
#1 ./hello_world: error while loading shared libraries: libprotobuf.so.3.11.2.0: cannot open shared object file: No such file or directory  #2 Cannot allocate memory [12]

### ISSUE THREAD

**Issue by 1908639561** [p4lang/p4app-switchML#15]
Hi,
I ran **make RDMA=1** under **p4app-switchML/dev_root/client_lib/**, then **make RDMA=1** under **p4app-switchML/dev_root/examples/**, and finally ran **. /hello_world** under p4app-switchML/dev_root/ build/bin/ . But it shows: "./hello_world: error while loading shared libraries: libprotobuf.so.3.11.2.0: cannot open shared object file: No such file or directory".
![1657013264812](https://user-images.githubusercontent.com/95405577/177296890-04119860-dbcd-4432-9ac8-045e1e497e7d.png)

Environment:
- Ubuntu16.04
- Python 3.8.3
- ConnectX-6 NIC

**Comment by OasisArtisan** [comment]
You have to compile the needed third party libraries which in your case is only GRPC. 
Go to dev_root/third_party and run `make RDMA=1`. This will compile GRPC then print an important message that you need to follow in order to register the GRPC library in your system.

Next time, you can just run `make RDMA=` in dev_root and it will perform all needed steps.

Let me know if it doesn't work out.

**Comment by 1908639561** [comment]
Thank you very much for your help, I have been able to start this example, but it has the following exception again, I don't know what is the cause, can you give me some advice?

![1657167811183](https://user-images.githubusercontent.com/95405577/177690816-f5e1f270-5bc4-4270-893f-a078a0538d28.png)

My switchml.cfg is as follows ,and placed it in the ~/p4app-switchML/dev_root/build/bin with hello_world directory：

[switchml.txt](https://github.com/p4lang/p4app-switchML/files/9060362/switchml.txt)

**Comment by lvleiai123** [comment]
i have this same porblem  as you，has you solved it ？

```
开始时间为2022-07-08 07:45:56
F0708 07:46:02.541637  6034 rdma_endpoint.cc:163] Check failed: buf != MAP_FAILED && buf == requested_address Error allocating memory region: Cannot allocate memory [12]
*** Check failure stack trace: ***
    @     0x7ff262a390cd  google::LogMessage::Fail()
    @     0x7ff262a3af33  google::LogMessage::SendToLog()
    @     0x7ff262a38c28  google::LogMessage::Flush()
    @     0x7ff262a38e49  google::LogMessage::~LogMessage()
    @     0x7ff262a39efa  google::ErrnoLogMessage::~ErrnoLogMessage()
    @     0x7ff2745eb57f  switchml::RdmaEndpoint::AllocateAtAddress()
    @     0x7ff2745e74b4  switchml::RdmaConnection::RdmaConnection()
    @     0x7ff2745e5cf6  switchml::RdmaBackend::SetupWorker()
    @     0x7ff2745d8d78  switchml::Context::Start()
    @     0x7ff2745356d1  c10d::ProcessGroupGloo::ProcessGroupGloo()
    @     0x7ff274383ec6  _ZZN8pybind1112cpp_function10initializeIZNOS_6detail8initimpl7factoryIZN5torch11distributed4c10d12_GLOBAL__N_19c10d_initEP7_objectEUlRKSt10shared_ptrIN4c10d5StoreEEiiNSt6chrono8durationIlSt5ratioILl1ELl1000EEEEE17_PFNS2_9void_typeEvEFSB_INSC_16ProcessGroupGlooEESG_iiSL_ESO_E7executeINS_6class_ISQ_JSR_EEEJNS_3argESX_SX_NS_5arg_vENS_10call_guardIJNS_18gil_scoped_releaseEEEEEEEvRT_DpRKT0_EUlRNS2_16value_and_holderESG_iiSL_E_vJS19_SG_iiSL_EJNS_4nameENS_9is_methodENS_7siblingENS2_24is_new_style_constructorESX_SX_SX_SY_S11_EEEvOS12_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES1Q_
    @     0x7ff273d70ea4  pybind11::cpp_function::dispatcher()
    @     0x561799624714  cfunction_call
    @     0x5617995f49ef  _PyObject_MakeTpCall
    @     0x561799585e19  method_vectorcall.cold.2732
    @     0x5617995e87f7  _PyObject_Call
    @     0x5617995602eb  slot_tp_init.cold.2342
    @     0x5617995fa94b  type_call
    @     0x7ff273d6eda9  pybind11_meta_call
    @     0x5617995f49ef  _PyObject_MakeTpCall
    @     0x56179967b853  _PyEval_EvalFrameDefault
    @     0x5617996328e2  _PyEval_EvalCode
    @     0x561799633527  _PyFunction_Vectorcall
    @     0x5617995aa90b  _PyEval_EvalFrameDefault.cold.2975
    @     0x5617996328e2  _PyEval_EvalCode
    @     0x561799633527  _PyFunction_Vectorcall
    @     0x5617995aa90b  _PyEval_EvalFrameDefault.cold.2975
    @     0x561799633753  _PyFunction_Vectorcall
    @     0x5617995aaebb  _PyEval_EvalFrameDefault.cold.2975
    @     0x561799633753  _PyFunction_Vectorcall
    @     0x5617995aaebb  _PyEval_EvalFrameDefault.cold.2975
    @     0x5617996328e2  _PyEval_EvalCode
Aborted (core dumped)
```

**Comment by 1908639561** [comment]
@lvleiai123 ,
I'm very sorry, I don't have a solution yet. If you have a solution afterwards, I'd appreciate you telling me about it.

**Comment by OasisArtisan** [comment]
You must run the controller to use the DPDK or RDMA backends. Without the controller you can only run with the dummy backend which is used usually for debugging (no real communication happens).

**Comment by 1908639561** [comment]
@OasisArtisan, thank you very much for your help, I've been able to run the "hello_world" example on the client side! I would also like to do a joint test with the switch afterwards. 
![image](https://user-images.githubusercontent.com/95405577/178021675-f9d57a40-c3f5-4900-a936-65bdd8637f02.png)

But I had some trouble on the switch side. Could you please take a look at the following issue?
https://github.com/p4lang/p4app-switchML/issues/13#issue-1292901371

**Comment by lvleiai123** [comment]
@1908639561 i have been run switch and controller already，however this problem is still happed.

```
bf-sde.pm> show
-----+----+---+----+-------+----+--+--+---+---+---+--------+----------------+----------------+-
PORT |MAC |D_P|P/PT|SPEED  |FEC |AN|KR|RDY|ADM|OPR|LPBK    |FRAMES RX       |FRAMES TX       |E
-----+----+---+----+-------+----+--+--+---+---+---+--------+----------------+----------------+-
5/0  | 6/0| 12|1/12|100G   | RS |Ds|Au|YES|ENB|UP |  NONE  |               0|               0|
7/0  | 5/0| 20|1/20|100G   | RS |Ds|Au|YES|ENB|UP |  NONE  |               0| [](url)             11|
9/0  | 4/0| 28|1/28|100G   | RS |Ds|Au|YES|ENB|UP |  NONE  |               9|               2|
11/0 | 3/0| 36|1/36|100G   | RS |Ds|Au|YES|ENB|UP |  NONE  |               2|               5|
![Snipaste_2022-07-09_10-07-36](https://user-images.githubusercontent.com/59639597/178087687-bec73eb8-38b6-4bd1-9dc2-2d411312ab8b.png)

```
Furthermore，i can run "hello world" success with dummy ,but when i use dpdk or rdma backend，i got "Check failed: buf != MAP_FAILED && buf == requested_address Error allocating memory region: Cannot allocate memory [12]"

**Comment by 1908639561** [comment]
@lvleiai123 , have you set up this script?
https://github.com/p4lang/p4app-switchML/tree/main/dev_root/scripts

**Comment by lvleiai123** [comment]
i haven't run this scriptsa and i will try this now  .  we can get "DEV" by run “ibv_devices”,  how can i get another “REGS”.

**Comment by 1908639561** [comment]
I don't think it should need to be changed if you're using the ConnectX-5/6 NIC.

**Comment by 1908639561** [comment]
@lvleiai123 ,
What version of SDE are you using? Is your "switchml.cfg" file not properly configured?

**Comment by lvleiai123** [comment]
SDE = 9.5.0 , here are my configure ，i'm afraid i have configured correctlly
[switchml.txt](https://github.com/p4lang/p4app-switchML/files/9075788/switchml.txt)

**Comment by 1908639561** [comment]
@lvleiai123 ,
 Indeed, you can try to modify different values, and the value of "rank" in this file should be different in different clients. Also the official test was done on "9.6.0", I think the "SDE" version may also need to be "9.6.0" or higher.

**Comment by lvleiai123** [comment]
i can also run hello world successfully by default configureation in switchml.cfg.
but when i change the  configuration  “backend = dummy” into “backend = rdma” in  switchml.cfg ,i will get errors like this
![Snipaste_2022-07-09_14-44-24](https://user-images.githubusercontent.com/59639597/178095005-750e5f4e-73fa-4d29-8726-46a7628c4564.png), you can try for it

**Comment by AmedeoSapio** [comment]
Hi,
the SDE version 9.7 has changed the name of the pktgen table, so the controller code that worked for 9.6 and earlier versions does not work with 9.7+. I have now committed the changes to make it work with 9.7+.
@lvleiai123 I suggest to update to the a newer SDE, but if you want to keep using 9.5, do not pull the latest commit.

Regarding the "Cannot allocate memory [12]" error, I think that you run out of memory in the hugepages. 
Just out of curiosity, can you please try to use `packet_numel=64` and `max_outstanding_packets=1` and check if the error still happens? This is reducing the amount of memory allocated. 

Anyway, to solve the issue you should enable 1GB hugepages. Please confirm if this solves the problem. 

Finally, regarding disabling the ICRC check, the script we provide works for Mellanox CTX 5 and 6, but for any other NIC you need to ask the NIC vendor how this can be done. If you find out how to do this for a different NIC, it would be great to let us know or send a PR with the script, so that we can add that to the repo.

**Comment by 1908639561** [comment]
@AmedeoSapio  @OasisArtisan @lvleiai123，hi，
 I have been able to run "hello_world". But the client only seems to be sending packets, but never receiving packets from the switch. I am using SDE-9.8.0.But I guess I may need to try using SDE-9.7.0 in the future.
I have changed my switchml.cfg according to this issue：https://github.com/p4lang/p4app-switchML/issues/8#issue-1167374645
[switchml.cfg.txt](https://github.com/p4lang/p4app-switchML/files/9076145/switchml.cfg.txt)
![1657356392545](https://user-images.githubusercontent.com/95405577/178098808-5a64ca99-d910-439e-b64f-6627df06f7f9.png)
![image](https://user-images.githubusercontent.com/95405577/178098825-864202d1-12f4-4fdb-936d-59e3aabca678.png)

**Comment by 1908639561** [comment]
I use "python3 switchml.py --switch-mac 00:90:fb:70:64:b9 --switch-ip 192.168.136.148" to run my controller.And my switch NIC information is as follows：
![1657358096571](https://user-images.githubusercontent.com/95405577/178099668-419ce09c-8416-4e1c-8334-802caf8ba355.png)

**Comment by AmedeoSapio** [comment]
Hi,
the `--switch-mac` and `--switch-ip` parameters are the addresses that the switch uses while acting as endpoint, to send/receive packets to the RDMA NICs. These do not need to be addresses of a real NIC on your system.

For `--switch-mac` you can use the default value `00:11:22:33:44:55`, as long as no other NIC in your testbed has this exactly same MAC address. 
For `--switch-ip` you need to provide an address, not used by anyone else, in the same subnet as the IPs of your RDMA NICs.
As an example, if you have 2 worker nodes, the first host RDMA NIC has IP 10.0.0.1/24 and the second one has 10.0.0.2/24, you should provide something like `--switch-ip 10.0.0.100`.

**Comment by 1908639561** [comment]
Hi, @AmedeoSapio . Thank you for your reply！
I did what you said, but it still doesn't seem to work.The client is always waiting for the jobs to complete.I am using SDE-9.9.0.
![image](https://user-images.githubusercontent.com/95405577/178129064-20ef0629-9dcc-456e-9f09-199411ddfeca.png)

My RDMA NIC's status:
**ens6f1:**
- Link encap:Ethernet  
- HWaddr 10:70:fd:06:fa:4d  
- inet addr:10.0.0.4  
- Bcast:0.0.0.0  
- Mask:255.255.255.0

![image](https://user-images.githubusercontent.com/95405577/178128970-b46012fb-8701-4721-876a-315819aea340.png)

My ports.yaml:
![image](https://user-images.githubusercontent.com/95405577/178128976-2e9c9bb8-f4b1-4661-85ab-e64cb85f1033.png)

My switchml.cfg:
[switchml.cfg.txt](https://github.com/p4lang/p4app-switchML/files/9078307/switchml.cfg.txt)

**Comment by 1908639561** [comment]
Hi, @AmedeoSapio ，
I see in this question that we can only use ports below 64 to connect to the server, https://github.com/p4lang/p4app-switchML/issues/6#issuecomment-1063497997has this restriction not been lifted yet please?This is because the switches I use all have port numbers of 64 or more.

![image](https://user-images.githubusercontent.com/95405577/178148184-04eb993d-8754-4114-95c2-fa9ff9538517.png)

**Comment by AmedeoSapio** [comment]
Hi @1908639561,
that restriction is not present anymore, so you shouldn't have any problem with a 2-pipes switch (as long as you don't explicitly enable the folded pipeline in the controller).
Since you are mentioning that the switch is a 2 pipes switch, note that you can only use `packet_numel = 64` (see this other  https://github.com/p4lang/p4app-switchML/issues/6#issuecomment-1070319732 in that same issue). 
Please check if changing this value solves your problem.

**Comment by 1908639561** [comment]
Hi, @AmedeoSapio ，
I've changed its value, but it still doesn't work properly.
[switchml.cfg.txt](https://github.com/p4lang/p4app-switchML/files/9080621/switchml.cfg.txt)

**Comment by AmedeoSapio** [comment]
@1908639561 How many packets in/out that port do you see with the `pm show` command when you start the client?

**Comment by lvleiai123** [comment]
i have two  nodes，it have  been run successfully， i can see them in controller  by command "show_rdma_workers"。
```
SwitchML>show_rdma_workers
                                                   Received              Sent
 Worker ID     Worker MAC        Worker IP     Packets  /    Bytes      Packets  /    Bytes
     0      b8:ce:f6:74:73:7b     2.2.2.3         0     /      0           0     /      0
     1      b8:ce:f6:74:69:c3     2.2.2.4         0     /      0           0     /      0
```
here are info when i run train program in node work3：
```
[switchml.txt](https://github.com/p4lang/p4app-switchML/files/9088703/switchml.txt)
[switchml.txt](https://github.com/p4lang/p4app-switchML/files/9088703/switchml.txt)

(base) root@work3:/imagenet#  python main.py -a resnet50 --dist-url 'tcp://2.2.2.3:10000' --dist-backend 'gloo'  --world-size 2 --rank 0  /imagenet/tiny-imagenet-200/
开始时间为2022-07-11 10:04:31
=> creating model 'resnet50'
Epoch: [0][  0/196]     Time  3.698 ( 3.698)    Data  0.843 ( 0.843)    Loss 7.1413e+00 (7.1413e+00)    Acc@1   0.00 (  0.00)   Acc@5   0.78 (  0.78)
Epoch: [0][ 10/196]     Time  1.794 ( 1.969)    Data  0.000 ( 0.077)    Loss 8.1934e+00 (7.1185e+00)    Acc@1   0.78 (  0.50)   Acc@5   2.73 (  2.41)
Epoch: [0][ 20/196]     Time  1.820 ( 1.889)    Data  0.000 ( 0.040)    Loss 7.2121e+00 (7.3330e+00)    Acc@1   0.00 (  0.39)   Acc@5   1.95 (  2.29)
Epoch: [0][ 30/196]     Time  1.794 ( 1.860)    Data  0.000 ( 0.027)    Loss 5.8432e+00 (7.0244e+00)    Acc@1   0.39 (  0.50)   Acc@5   3.91 (  2.65)
```
work4：
```
(base) root@work4:/imagenet# python main.py -a resnet50 --dist-url 'tcp://2.2.2.3:4791' --dist-backend 'gloo'  --world-size 2 --rank 1  /imagenet/tiny-imagenet-200/
开始时间为2022-07-11 10:57:33
=> creating model 'resnet50'
Epoch: [0][  0/196]     Time  3.624 ( 3.624)    Data  1.088 ( 1.088)    Loss 7.0714e+00 (7.0714e+00)    Acc@1   0.39 (  0.39)   Acc@5   1.17 (  1.17)
Epoch: [0][ 10/196]     Time  1.797 ( 1.980)    Data  0.000 ( 0.099)    Loss 8.1733e+00 (7.0992e+00)    Acc@1   0.00 (  0.43)   Acc@5   1.17 (  2.59)
```

However, i don't understand why node working with “TCP” ，also，  " Received  "and “Sent” is both 0 by  "show_rdma_workers" in controller.  All  Packets I captured in node work3 or work4  through "tcpdump" are TCP ,no UDP at all.
 
i have already configured "RDMA" in switchml.cfg as below 。

Finally，i also don't understand clearly if  “dist-url ”  is the ip of mellanox network card。
[switchml.txt](https://github.com/p4lang/p4app-switchML/files/9088723/switchml.txt)
[switchml.txt](https://github.com/p4lang/p4app-switchML/files/9088723/switchml.txt)

**Comment by 1908639561** [comment]
> @1908639561 How many packets in/out that port do you see with the `pm show` command when you start the client?

@AmedeoSapio , It is in this state：
![image](https://user-images.githubusercontent.com/95405577/178396878-bf0948b4-98a2-4cb1-95b3-d8671b528915.png)

**Comment by 1908639561** [comment]
I'm sorry, I think I made a fatal mistake because I reinstalled my switch system as ubuntu 18.04. So I was using the default normal user and my controller didn't have permission to handle the packets. After I recompiled SwitchML and ran the controller when I switched to root, I am now able to run "hello_world".
![image](https://user-images.githubusercontent.com/95405577/178636812-4fa07d74-7c86-4cd3-ab47-22ee01b6d762.png)
